### ISSUE TITLE
Update Registration Flow

### ISSUE THREAD

**Issue by setzeus** [Trust-Machines/BNS-V2#10]
**Description**
This is the story, or macro feature, that captures all the use-cases, features & requirements for the updated Register userflow. 

At a high level, this boils down to refactoring for the two following core purposes:

1. Splitting Native Registration Flow To Two Options
The current registration flow is a worst of both worlds situation in that it involves multiple steps *&* it's not protected from sniping. To solve both problems at once, a solution suggested by Hank / seen in ENS  is to offer two different registration flows, both of which disincentive front-running. 

The current registration process involves calling (name-preorder), then (name-register).

We propose updating this to involve two flows with the following differences:

A: A 'fast' one-block registration function: (name-claim-fast)
B: A 'slow' two-block registration function: (name-preorder), (name-reveal)
 
To further punish front-running, in path (A), even though the user, if not sniped, will get the name in one block, they _**cannot**_ take any meaningful action with until the **_next_** block. They must wait a single additional block before they can list or transfer it. With this additional block, the timelines match up for when both paths can actually list or transfer their namespace (aka both paths take up two blocks). 

Additionally, this registration flow must be accounted for in the new 'mng-register' function tracked in #8. 

**User Stories**
- User can claim a BNS-v2 token in one block
- User can use the current two-block claim logic
```[tasklist]
### Tasks
- [ ] https://github.com/Trust-Machines/BNS-V2/issues/11
- [ ] https://github.com/Trust-Machines/BNS-V2/issues/15
- [ ] https://github.com/Trust-Machines/BNS-V2/issues/19
```
